Repository RUGSoftEng/2018-PyDash.io, pull requests merged in 2018-03, with the labels that each got.

#22 Creates the starting point of our application and its architecture
  Pipfile
  pydash/Pipfile
  pydash/Pipfile.lock
  pydash/config.py
  pydash/file
  pydash/pydash.py
  pydash/pydash_app/__init__.py
  pydash/pydash_app/user/__init__.py
  pydash/pydash_app/user/user.py
  pydash/pydash_app/user/user_repository.py
  pydash/pydash_web/__init__.py
  pydash/pydash_web/controller/__init__.py
  pydash/pydash_web/controller/dashboard.py
  pydash/pydash_web/controller/login.py
  pydash/pydash_web/controller/logout.py
  pydash/pydash_web/forms.py
  pydash/pydash_web/routes.py
  pydash/pydash_web/templates/base.html
  pydash/pydash_web/templates/dashboard.html
  pydash/pydash_web/templates/index.html
  pydash/pydash_web/templates/login.html
Labels: back-end

#54 Add barebones functionality to fetch data from a dashboard
  pydash/Pipfile
  pydash/Pipfile.lock
  pydash/pydash_app/dashboard/__init__.py
  pydash/pydash_app/dashboard/fetch.py
Labels: back-end

#71 Backend/periodic tasks
  pydash/Pipfile
  pydash/Pipfile.lock
  pydash/pydash_app/impl/periodic_tasks/__init__.py
  pydash/pydash_app/impl/periodic_tasks/pqdict_iter_upto_priority.py
  pydash/pydash_app/impl/periodic_tasks/queue_nonblocking_iter.py
  pydash/pydash_app/impl/periodic_tasks/task_scheduler.py
Labels: back-end

#75 Redirects user to login screen when logging out
  pydash-front/src/logout/Logout.js
Labels: front-end

#72 Backend/dashboard and repo
  pydash/pydash_app/dashboard/__init__.py
  pydash/pydash_app/dashboard/dashboard.py
  pydash/pydash_app/dashboard/dashboard_repository.py
  pydash/pydash_app/user/user.py
  pydash/pydash_web/__init__.py
  pydash/pydash_web/controller/dashboards.py
Labels: back-end

#93 Backend/update data fetch
  pydash/pydash_app/impl/fetch.py
Labels: back-end

#92 Mock dashboard aggregates data.
  docs/.tool-versions
  pydash/.tool-versions
  pydash/pydash_web/controller/dashboards.py
Labels: back-end, front-end

#97 Backend/data aggregation
  pydash/pydash_app/dashboard/aggregator.py
  pydash/pydash_app/dashboard/dashboard.py
  pydash/pydash_app/dashboard/endpoint.py
  pydash/pydash_app/dashboard/endpoint_call.py
Labels: back-end

#99 Backend/mock dashboard
  build_and_run.sh
  pydash/pydash_web/controller/dashboards.py
Labels: back-end
