Repository RUGSoftEng/2018-PyDash.io, pull requests merged in 2018-04, with the labels that each got.

#103 Basic Graphs (with fake data)
  pydash-front/package-lock.json
  pydash-front/package.json
  pydash-front/src/App.js
  pydash-front/src/App.test.js
  pydash-front/src/app/dashboard/Dashboard.js
  pydash-front/src/app/dashboard/Logout.js
  pydash-front/src/app/dashboard/Sidebar.js
  pydash-front/src/app/overview/DashTile.js
  pydash-front/src/app/overview/DashTileGrid.js
  pydash-front/src/app/overview/DashboardVisitsGraph.js
  pydash-front/src/app/overview/Overview.js
  pydash-front/src/app/overview/overview.css
  pydash-front/src/app/statistics/Statistics.js
  pydash-front/src/dashboard/Dashboard.css
  pydash-front/src/dashboard/Dashboard.js
  pydash-front/src/images/logo.png
  pydash-front/src/images/logo_inverse.png
  pydash-front/src/login/Login.js
  pydash-front/src/logo.png
  pydash-front/src/overview/DashTile.js
  pydash-front/src/overview/DashTileGrid.js
  pydash-front/yarn.lock
  pydash/pydash_web/__init__.py
  pydash/pydash_web/controller/dashboards.py
  pydash/pydash_web/routes.py
Labels: back-end, front-end

#109 fixes #106 the duplicate returning of mock dashboard data
  pydash/pydash_web/controller/dashboards.py
Labels: back-end, bug

#112 Backend/dbdb api hotfix
  pydash/pydash_web/controller/dashboards.py
Labels: back-end

#119 Return user info from backend after login
  pydash/pydash_web/controller/login.py
Labels: back-end

#118 Shows the name of currently logged in user in sidebar
  pydash-front/src/App.js
  pydash-front/src/app/dashboard/Dashboard.js
  pydash-front/src/app/dashboard/Logout.js
  pydash-front/src/login/Login.js
Labels: front-end

#137 Backend/logger
  .gitignore
  pydash/pydash_app/impl/logger/__init__.py
  pydash/pydash_app/impl/logger/logger.py
  pydash/pydash_web/__init__.py
Labels: back-end

#153 Backend/account creation
  pydash/pydash_app/user/__init__.py
  pydash/pydash_web/controller/__init__.py
  pydash/pydash_web/controller/register_user.py
  pydash/pydash_web/routes.py
Labels: back-end

#156 Split pydash_web into "api" and "static" blueprints, and correctly serve static files
  pydash/pydash_web/__init__.py
  pydash/pydash_web/api.py
  pydash/pydash_web/api_routes.py
  pydash/pydash_web/static.py
  pydash/pydash_web/static_routes.py
Labels: back-end

#134 Frontend/sounds2
  pydash-front/package.json
  pydash-front/sounds/320664__pizzaiolo__lovelyboot1.flac
  pydash-front/sounds/320664__pizzaiolo__lovelyboot1.mp3
  pydash-front/sounds/320664__pizzaiolo__lovelyboot1.ogg
  pydash-front/sounds/320664__pizzaiolo__lovelyboot1.webm
  pydash-front/src/app/dashboard/Dashboard.js
  pydash-front/src/app/dashboard/Logout.js
  pydash-front/src/app/dashboard/Sidebar.js
  pydash-front/src/app/dashboard/pop.mp3
  pydash-front/src/app/dashboard/woosh.mp3
  pydash-front/src/login/Login.js
  pydash-front/src/login/boot.mp3
  pydash-front/yarn.lock
Labels: back-end

#182 Testing/sign in
  README.md
  pydash-front/src/app/boards/GraphGrid.js
  pydash-front/src/app/dashboard/Logout.js
  pydash-front/src/app/overview/DashTileGrid.js
  pydash-front/src/login/Auth.js
  pydash-front/src/login/Login.js
  pydash/Pipfile
  pydash/Pipfile.lock
  pydash/conftest.py
  pydash/pytest.ini
  pydash/tests.features.test_salad_example/test_salad_example-browser.html
  pydash/tests.features.test_salad_example/test_salad_example-browser.png
  pydash/tests/conftest.py
  pydash/tests/features/salad_example.feature
  pydash/tests/features/sign_in.feature
  pydash/tests/features/test_sign_in.py
  pydash/tests/features/test_visiting_pydash.py
  pydash/tests/features/visiting_pydash.feature
Labels: testing

#192 Frontend/overview
  pydash-front/src/App.js
  pydash-front/src/app/boards/Board.js
  pydash-front/src/app/boards/GraphGrid.js
  pydash-front/src/app/dashboard/Dashboard.js
  pydash-front/src/app/dashboard/Logout.js
  pydash-front/src/app/overview/DashTile.js
  pydash-front/src/app/overview/DashTileGrid.js
  pydash-front/src/app/overview/overview.css
  pydash-front/src/index.js
  pydash-front/src/login/Auth.js
  pydash-front/src/login/Login.js
Labels: front-end

#191 Fixes front-end on different port; useful error handling while logging in
  pydash-front/src/app/boards/GraphGrid.js
  pydash-front/src/app/dashboard/Logout.js
  pydash-front/src/app/overview/DashTileGrid.js
  pydash-front/src/index.js
  pydash-front/src/login/Auth.js
  pydash-front/src/login/Login.js
Labels: bug, front-end

#198 Frontend/dashboard detail
  pydash-front/package.json
  pydash-front/src/App.js
  pydash-front/src/app/boards/Board.js
  pydash-front/src/app/boards/GraphGrid.js
  pydash-front/src/app/dashboard/DashboardPage.js
  pydash-front/src/app/dashboard/DashboardVisitsGraph.js
  pydash-front/src/app/dashboard/UniqueVisitorsPerDayPanel.js
  pydash-front/src/app/dashboard/VisitsPerDayPanel.js
  pydash-front/src/app/main_interface/Logout.js
  pydash-front/src/app/main_interface/MainInterface.js
  pydash-front/src/app/main_interface/Sidebar.js
  pydash-front/src/app/main_interface/pop.mp3
  pydash-front/src/app/main_interface/woosh.mp3
  pydash-front/src/app/overview/DashboardList.js
  pydash-front/src/app/overview/DashboardListItem.js
  pydash-front/src/app/overview/Overview.js
  pydash-front/src/utils.js
  pydash-front/yarn.lock
Labels: front-end

#201 Add exception handling for historic endpoint call fetching
  pydash/flask_monitoring_dashboard_client/__init__.py
  pydash/pydash_app/dashboard/services/fetching.py
  pydash/pydash_app/dashboard/services/seeding.py
Labels: back-end, bug

#205 Backend/api return state error
  pydash/pydash_web/controller/dashboards.py
Labels: back-end

#217 Backend/support fmd v1.12.0
  pydash/pydash_app/dashboard/services/fetching.py
Labels: back-end
